-- Set up strict categories to prevent bad data entries
CREATE TYPE user_role AS ENUM ('super_admin', 'hostel_admin', 'student');
CREATE TYPE meal_type AS ENUM ('breakfast', 'lunch', 'dinner', 'tea');
CREATE TYPE booking_status AS ENUM ('active', 'cancelled', 'consumed');
CREATE TYPE payment_status AS ENUM ('pending', 'verified', 'rejected');


-- Stores basic hostel info. 
-- admin_id is left blank at first to avoid a circular dependency error when creating tables.
CREATE TABLE hostels (
    hostel_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    invite_code VARCHAR(20) UNIQUE NOT NULL,
    admin_id UUID, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- All users (students and admins). 
-- The primary key 'id' needs to match the secure UUID generated by Supabase Auth.
CREATE TABLE users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role user_role NOT NULL DEFAULT 'student',
    hostel_id INT REFERENCES hostels(hostel_id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    current_balance DECIMAL(10, 2) DEFAULT 0.00,
    is_banned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Now that the users table exists, we can safely link the hostel to its admin.
ALTER TABLE hostels 
ADD CONSTRAINT fk_admin 
FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL;


-- Daily food options. 
-- The UNIQUE constraint stops admins from accidentally creating the exact same combo twice on the same day.
CREATE TABLE menus (
    menu_id SERIAL PRIMARY KEY,
    hostel_id INT REFERENCES hostels(hostel_id) ON DELETE CASCADE,
    serve_date DATE NOT NULL,
    meal_time meal_type NOT NULL,
    combo_name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    UNIQUE(hostel_id, serve_date, meal_time, combo_name) 
);

-- Tracks who booked what and when.
CREATE TABLE bookings (
    booking_id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    menu_id INT REFERENCES menus(menu_id) ON DELETE CASCADE,
    booking_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    status booking_status DEFAULT 'active'
);

-- Logs payment screenshots. 
-- The transaction_id is extracted later by the Python OCR script.
CREATE TABLE payments (
    payment_id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    transaction_id VARCHAR(50) UNIQUE,
    receipt_image_url TEXT NOT NULL,
    extracted_date DATE,
    status payment_status DEFAULT 'pending',
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- ==========================================
-- AUTOMATION TRIGGERS
-- ==========================================

-- Trigger A: Deduct balance when a booking is made
CREATE OR REPLACE FUNCTION fn_deduct_balance_on_booking()
RETURNS TRIGGER AS $$
DECLARE
    meal_price DECIMAL(10,2);
BEGIN
    -- Get the price of the booked meal
    SELECT price INTO meal_price FROM menus WHERE menu_id = NEW.menu_id;
    
    -- Deduct the meal cost from the user's balance
    UPDATE users 
    SET current_balance = current_balance - meal_price
    WHERE id = NEW.user_id;

    -- Auto-ban the user if their balance drops below zero
    UPDATE users
    SET is_banned = TRUE
    WHERE id = NEW.user_id AND current_balance < 0.00;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_after_booking_insert
AFTER INSERT ON bookings
FOR EACH ROW EXECUTE FUNCTION fn_deduct_balance_on_booking();


-- Trigger B: Add funds when a payment is verified
CREATE OR REPLACE FUNCTION fn_credit_balance_on_verification()
RETURNS TRIGGER AS $$
BEGIN
    -- Only run this if the status was just changed to 'verified'
    IF NEW.status = 'verified' AND OLD.status = 'pending' THEN
        
        -- Add the approved amount to the user's balance
        UPDATE users 
        SET current_balance = current_balance + NEW.amount
        WHERE id = NEW.user_id;

        -- If their balance is out of the negative, lift the ban
        UPDATE users
        SET is_banned = FALSE
        WHERE id = NEW.user_id AND current_balance >= 0.00;
        
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_after_payment_update
AFTER UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION fn_credit_balance_on_verification();


-- All schema related info.

-- this is for checcking whether food was delivered or not

ALTER TABLE menus 
ADD COLUMN is_delivered BOOLEAN DEFAULT FALSE;